
DROP TABLE IF EXISTS TBL_EMPLOYEE;

CREATE DATABASE KRG_3B
USE KRG_3B

CREATE TABLE TBL_EMPLOYEE (
  EMP_ID INT IDENTITY(101, 2),
  EMP_NAME VARCHAR(MAX) ,
  MANAGER_ID INT 
);

INSERT INTO TBL_EMPLOYEE(EMP_NAME) VALUES('Jyoti')
INSERT INTO TBL_EMPLOYEE(EMP_NAME) VALUES('ABC')

SELECT * FROM TBL_EMPLOYEE



CREATE TABLE TBL_AUTHOR (
  AUTHOR_ID INT PRIMARY KEY,
  AUTHOR_NAME VARCHAR(MAX),
  COUNTRY VARCHAR(MAX)
)

CREATE TABLE TBL_BOOKS (
  BOOK_ID INT PRIMARY KEY,
  BOOK_TITLE VARCHAR(MAX),
  AUTHORID INT FOREIGN KEY REFERENCES TBL_AUTHOR(AUTHOR_ID)
)
INSERT INTO TBL_AUTHOR (AUTHOR_ID, AUTHOR_NAME, COUNTRY)
VALUES 
  (1, 'J.K. Rowling', 'UK'),
  (2, 'George R.R. Martin', 'USA'),
  (3, 'Chetan Bhagat', 'India');

INSERT INTO TBL_BOOKS (BOOK_ID, BOOK_TITLE, AUTHORID)
VALUES
  (101, 'Harry Potter', 1),
  (102, 'A Game of Thrones', 2),
  (103, 'Five Point Someone', 3),
  (104, 'The Casual Vacancy', 1),
  (105, 'A Clash of Kings', 2);

 SELECT * FROM TBL_AUTHOR;
 SELECT * FROM TBL_BOOKS

SELECT 
  B.BOOK_TITLE AS 'BOOK TITLE', 
  A.AUTHOR_NAME, 
  A.COUNTRY
FROM TBL_BOOKS AS B
INNER JOIN TBL_AUTHOR AS A
ON B.AUTHORID = A.AUTHOR_ID



SELECT 
  E1.EMP_NAME AS [EMP_NAME], 
  E2.EMP_NAME AS [MANAGER_NAME]
FROM TBL_EMPLOYEE AS E1
INNER JOIN TBL_EMPLOYEE AS E2
ON E1.MANAGER_ID = E2.EMP_ID


